# Generated by Django 5.1.3 on 2024-11-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='breated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descriptionb',
            new_name='description',
        ),
    ]
